### ISSUE TITLE
Build a 404 Page

### ISSUE THREAD

**Issue by kalebheitzman** [HeitzmanCo/ChristChurchRaleigh-Theme#13]
Need design ideas from @jeremytackett

**Comment by kalebheitzman** [comment]
I've added a generic not found template. We can customize to be a site map or something...

**Comment by kalebheitzman** [comment]
Do you want to make this hymn 404?

**Comment by jeremytackett** [comment]
Haha. No. I'll write copy for this page on Monday or Tuesday.

**Comment by kalebheitzman** [comment]
Generic 404 page now exists.
