### ISSUE TITLE
Implement Shopify Functionality into site

### ISSUE THREAD

**Issue by kalebheitzman** [HeitzmanCo/ChristChurchRaleigh-Theme#19]
Look into adding Shopify functionality to site

**Comment by jeremytackett** [comment]
Like, lowest possible priority.

**Comment by kalebheitzman** [comment]
This will always be embedding shopify code into a text box. If you really need this I can add it. It wasn't that hard to setup. If not then I'll close the ticket. As far as creating a cart system you can go to https://climbkentucky.com and see that i've just used shopify on top of a pages. the shopping cart button is on the right hand side I think. Im not sure I would implement this on your site if you have  shopping cart front page on spotify already. One thing to be aware of is the you can embed shopify on Facebook too.

**Comment by kalebheitzman** [comment]
Also see #58
