### ISSUE TITLE
Main Events Listing Template

### ISSUE THREAD

**Issue by kalebheitzman** [HeitzmanCo/ChristChurchRaleigh-Theme#23]
![main-events-listing](https://cloud.githubusercontent.com/assets/313598/18642500/df97d8e4-7e6e-11e6-858a-dbddb0ac44e1.png)

**Comment by kalebheitzman** [comment]
Is this for an individual event or category specific events page?

**Comment by kalebheitzman** [comment]
OK I think I understand what this is in relation to #10. This will involve tagging an event sticky and then categorizing it as normal (I think.)

**Comment by jeremytackett** [comment]
Category specific events page. Like, youth events.

**Comment by kalebheitzman** [comment]
I think I'll load wufoo forms in a lightbox.

http://www.wufoo.com/guides/how-to-load-a-wufoo-form-inside-a-lightbox/

**Comment by kalebheitzman** [comment]
I've added this template type for pages. We can make it dynamic in that you can pass the category to the url or we can have a separate one for pages that need it. Just let me know either way.
