### ISSUE TITLE
Integrate Wufoo forms

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#26]
Let me know if you need our login info, or if I need to create a login for you.

**Comment by kalebheitzman** [comment]
Probably the best thing is to use embed code and have it pick up form styles from the site so it looks native. I'll have to look into this. I haven't done that in a while.

**Comment by jeremytackett** [comment]
Sample embed code (JavaScript):

<div id="wufoo-r1akjry71i4sc2o">
Fill out my <a href="https://christchurchraleigh.wufoo.com/forms/r1akjry71i4sc2o">online form</a>.
</div>
<script type="text/javascript">var r1akjry71i4sc2o;(function(d, t) {
var s = d.createElement(t), options = {
'userName':'christchurchraleigh',
'formHash':'r1akjry71i4sc2o',
'autoResize':true,
'height':'2323',
'async':true,
'host':'wufoo.com',
'header':'show',
'ssl':true};
s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'www.wufoo.com/scripts/embed/form.js';
s.onload = s.onreadystatechange = function() {
var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
try { r1akjry71i4sc2o = new WufooForm();r1akjry71i4sc2o.initialize(options);r1akjry71i4sc2o.display(); } catch (e) {}};
var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
})(document, 'script');</script>

**Comment by kalebheitzman** [comment]
Embedding this in the editor is just fine. I've embedded it into the Serve page as a link at the top. Not sure if it's supposed to display the form in page or go to the link but it works fine.
