### ISSUE TITLE
Add signup form for Christ Church mailing list 

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#30]
(under the "about" section, and a link in the footer under connect)

We already have this form from Mailchimp, we just need to link to it or embed it. When we get here, just let me know that you need the code and I'll get it.

**Comment by kalebheitzman** [comment]
Go ahead and give me the code for this.

**Comment by kalebheitzman** [comment]
Also, not seeing connect in the footer, do you mean contact us?

**Comment by jeremytackett** [comment]
Yes. I mean Contact Us.

**Comment by jeremytackett** [comment]
Link: http://christchurchraleigh.us10.list-manage2.com/subscribe?u=d2f42e047da51eff1a168dbc4&id=a1f03bfe64

**Comment by kalebheitzman** [comment]
Completed
