### ISSUE TITLE
Get web-specific email address

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#31]
info@christchurchraleigh.org

**Comment by kalebheitzman** [comment]
I'm going to add this as a theme option and then obfuscate it on the site where needed

**Comment by jeremytackett** [comment]
I don't know what that means. Sounds painful.

**Comment by jeremytackett** [comment]
Done. info@christchurchraleigh.org is now active and forwards to my email for monitoring.
