### ISSUE TITLE
Page Sidebar Tweaks / Additions

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#32]
- [x] Static Links (like the ones at http://www.christchurchraleigh.org/ministries/youth)

We won't need these on every page, but should be a sidebar option if that's possible.

- [x] Make the "Call to action" button a button. (Can we make it blue or something, some way for it to stand out?)

**Comment by kalebheitzman** [comment]
Static links can be added to the content section.

**Comment by kalebheitzman** [comment]
I've added some styles to the call to action button. We might consider using [font awesome](http://fontawesome.io/icons/) to add some sort of indicator to the button of whether it's a download, external links, etc.

**Comment by kalebheitzman** [comment]
I went ahead an added the ability to add the icons. You can see one on the youth page (once it's uploaded).
