### ISSUE TITLE
Calendar Tweaks

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#34]
- [x] Can we have the monthly calendar list "more" after a certain number of events, to keep the calendar from getting too big?
- [x] Reformat times from 6:30-7:30pm to 6:30 - 7:30 p.m.
- [ ] <strike>Would love if event details came up as a modal when an event was clicked, rather than going to a different page.</strike>
- [x] Start the days on Sunday instead of Monday. (In the calendar heading, blue bar)
- [ ] <strike>Need to be able to add exceptions to weekly / daily events. For example, sometimes a monthly event will occur on a different day or at a different time than the regular day/time. Or, occasionally a day/week/month will be taken off. (i.e., Stephen Ministry meets on the first Monday of the month, 11:30-12:30, but this month they’re meeting 11-12)</strike>
- [x] Need to specify locations for events in their own field. (Church, Chapel, name & address of location if offsite)
- [x] Doesn’t need to show “repeats until" on the event details page.
- [x] Create ACS calendar page

**Comment by kalebheitzman** [comment]
Checkout https://ccral.org/events/category:music

**Comment by kalebheitzman** [comment]
I've spent an insane amount of time updating this plugin (for the rest of the Grav community to use). We're good to go on it and I can start adding in these little tweaks.

**Comment by kalebheitzman** [comment]
Instead of "more", I'm creating a more intuitive modal system.

**Comment by kalebheitzman** [comment]
can't fix the 2 strikeouts. 1 legitimate (adding exceptions) and the second is bad design on the web. Modals are the devil if you don't have to use them
