### ISSUE TITLE
Design page type for Pastoral Care (front page)

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#36]
Info that will go on Pastoral Care Page -> http://www.christchurchraleigh.org/ministries/pastoral-care/pastoral-care-test/

Link to video: https://vimeo.com/168231802

![ink-image](https://cloud.githubusercontent.com/assets/22300799/18712274/b167e6ee-7fdb-11e6-98e2-67c50f529138.png)

![ink-image](https://cloud.githubusercontent.com/assets/22300799/18712281/b69fd59a-7fdb-11e6-968e-17584c647795.png)

**Comment by kalebheitzman** [comment]
I think this has been taken care of with modular page types.

**Comment by jeremytackett** [comment]
Agreed.

**Comment by jeremytackett** [comment]
I should've closed this before because I already designed this page. https://ccral.org/connect/pastoral-care
