### ISSUE TITLE
Design page type for Event Series

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#37]
Uses Bourbon.io Grid with images. (Maybe shaded images?)

![ink-image](https://cloud.githubusercontent.com/assets/22300799/18712356/085c4bfc-7fdc-11e6-87c5-de882453e7d7.png)

Example for the kind of content that would go in the grid:

[Page 36 - Back Cover.pdf](https://github.com/HeitzmanCo/ChristChurchRaleigh-Theme/files/485081/Page.36.-.Back.Cover.pdf)

**Comment by kalebheitzman** [comment]
Are the blocks image based or text based? Or both?

**Comment by kalebheitzman** [comment]
This has been resolved with the modular events addition
