### ISSUE TITLE
Build Sermons Module

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#40]
- [x] Page for Individual Sermon (maybe already exists?)
- [x] Front page module with most recent sermon
- [x] Index page of sermons searchable by tags

**Comment by kalebheitzman** [comment]
[https://ccral.org/sermons](https://ccral.org/sermons)

I've started this. Need to filter on specific tags/topics etc and then it will be functional.

**Comment by kalebheitzman** [comment]
What do you want the latest semon module to look like. I’ve uploaded the start of something to the front page.
