### ISSUE TITLE
Repost Kitchen

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#41]
- [x] Cards module
- [x] Grid module
- [x] Video module (vimeo, if it needs to be specific)
- [x] Text module (like for links on the current youth page)
- [x] Expander module

**Comment by kalebheitzman** [comment]
For video embeds, I think https://github.com/sommerregen/grav-plugin-mediaembed will work fine. You can use a regular content block and just paste the video link in the Markdown Image link format of
```
 ![Alt Text](http://vimeo.com/....)
```

**Comment by kalebheitzman** [comment]
Other than a weird admin bug (I may submit a patch) this plugin for video embeds works great. I posted the link in a content block for the kitchen and it's responsive and works seamlessly. Just like using wp shortcodes.
