### ISSUE TITLE
Repeating events not displaying properly

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#43]
When an event repeats weekly, the last instance isn't displaying.

For example, look at the "Middle School Bible Study" event. It should take place each Tuesday in September (6, 13, 20, 27), 6:30 - 7:45 p.m. The first three show up on the calendar, the fourth one (9/27) does not. 

Same thing happens with the last instance of Freshman Fellows, and the Midday Organ Recital.

**Comment by kalebheitzman** [comment]
I need to look at the reoccurring and repeating business logic in classes/events.php

**Comment by kalebheitzman** [comment]
Also, the first event isn't displaying an events by itself if no other rules are present.

**Comment by kalebheitzman** [comment]
The repeating issue is now fixed. The reason those were not working is because an until date had been set for them to repeat until the 26th.
