### ISSUE TITLE
Add Google Analytics to site

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#45]
I assume we'll do this toward the end of the process. Just putting it on the list.

**Comment by kalebheitzman** [comment]
Can you post your google analytics snippet here?

**Comment by jeremytackett** [comment]
`<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60740686-1', 'auto');
  ga('send', 'pageview');

</script>`

**Comment by kalebheitzman** [comment]
you can use ```code```

**Comment by jeremytackett** [comment]
Yeah. That.

**Comment by kalebheitzman** [comment]
This is now a theme option. Just add the Analytics ID to the theme config when we're ready.

UA-60740686-1
