### ISSUE TITLE
Get AJAX warning and error when saving a new module

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#48]
I have to save modules twice to get this error to go away. Once I save the second time, everything seems to work properly.
<img width="969" alt="screenshot 2016-09-25 11 14 52" src="https://cloud.githubusercontent.com/assets/22300799/18816157/5f8a7cc2-8311-11e6-9260-d9d499edb016.png">

**Comment by kalebheitzman** [comment]
well that's annoying

**Comment by kalebheitzman** [comment]
this might be a grav bug. I'm going to look into and see what i can figure out (nothing immediately.)

**Comment by kalebheitzman** [comment]
I've submitted a ticket to Grav about getting this fixed at https://github.com/getgrav/grav-plugin-admin/issues/805. I'm going to close this because it's out of my ability to troubleshoot/fix without doing some ugly hacking. It'd be better for it be fixed in core.

**Comment by kalebheitzman** [comment]
I've submitted a ticket to Grav about solving this solution. I'm pretty sure it's on their end so there's nothing I can do until they push and update. Closing and if it's still an issue before launch I'll create a new ticket in final run-throughs.
