### ISSUE TITLE
Need option to not display title above a page module

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#49]
Maybe this is just a setting you can show me, but for example, on the new pastoral care page I don't want "Pastoral Care Video", "Pastoral Care Mission", and "Care and Support" to actually display on the page.
https://ccral.org/connect/pastoral-care

**Comment by kalebheitzman** [comment]
So let's do this then. Let's disable titles on page modules in general and just add titles to the content section when needed. Using something like:

```
# Page Title

Page content, etc.
```

**Comment by kalebheitzman** [comment]
I've added a section for modules called extras (under options) where you can disable titles. By default they are disabled, so toggle them on to enable them.
