### ISSUE TITLE
Slider updates

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#50]

**Comment by jeremytackett** [comment]
- [ ] Change dot color on slider.
- [ ] Make slides and dots both go to the right.

**Comment by kalebheitzman** [comment]
Changed the dot to white.

**Comment by kalebheitzman** [comment]
http://slippry.com

**Comment by kalebheitzman** [comment]
Can't reverse the dots as far as I can tell.
