### ISSUE TITLE
Sermon search parameters

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#52]
- [x] Speaker
- [x] Liturgical Season
 - Advent
 - Christmas
 - Ordinary Time
 - Lent
 - Easter
- [x] Scripture Reading

Under "tags" I'll probably put some topical ones, but I don't think we want to be able to search those as a dropdown. Maybe a search box for people to put in their own searches? I don't know how well that would work, but it's something Callie suggested.

**Comment by kalebheitzman** [comment]
Those filters are now enabled. I'm working on an api call to automatically get the ID of the soundcloud link so we can skip embedding code in the content section and have it automatically generated in the template instead.
