### ISSUE TITLE
Build Staff page

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#53]
Super general example for layout: https://incarnation.org/about/clergy-staff-vestry/

Note: We won't separate full and part time Clergy. Just one clergy list.

**Comment by jeremytackett** [comment]
Format for page:
**Clergy**

**Staff*
Dropdowns under staff:
- Administrative Support
- Children’s Ministry
- Communications
- Facilities
- Finance Office
- Music
- Parish Life
- Youth Ministry (Liz, Martha C., Sandy)

**Vestry**

**Comment by kalebheitzman** [comment]
Page is built: https://ccral.org/staff
