### ISSUE TITLE
Staff page tweaks

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#57]
- [x] Change from "Staff" to "Clergy, Staff, and Vestry" (Vestry members aren't on staff)
- [x] Rounded squares instead of circles
- [x] Can we have the email/ext. not show up if the person doesn't have one (see Sextons under facilities staff)
- [x] I haven't decided what we'll do about bios yet. If we don't use them, can we either not make the name clickable, or have it go to their email? 
- [x] Make sections re-orderable
- [x] Can we have some sort of animation with the dropdown, so they don't just appear?

**Comment by kalebheitzman** [comment]
UI for name clickable is easy. I'm going to go ahead and set it to be clickable to URL if they have content in the content section (the bio would go here). If you decide to add bios we can automatically link them up and if not no worries. Also, I'll work on a solution that allows for a modal popup on email address so people can email directly from the site.
