### ISSUE TITLE
Set up online giving

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#59]
This is related to, but not specifically the same, as #11 . Call me or message me when you're ready to work on this and we can talk about it.

**Comment by kalebheitzman** [comment]
Need to touch base on this again. I'll be working all day sat and tomorrow evening knocking this and other things out.

**Comment by kalebheitzman** [comment]
Okay, so I've found this which will be the easiest to implement solution (and still look nice from what I can tell). 

https://support.authorize.net/authkb/index?page=content&id=A152&actp=search&viewlocale=en_US&searchid=1477764315926

It looks like a form will need generated though along with colors tweaked etc. Not sure If you guys can give me the credentials to login but that's where it has to be done.

**Comment by jeremytackett** [comment]
Sent you login info on FB messenger.

**Comment by kalebheitzman** [comment]
up and going. needs styled better
