### ISSUE TITLE
Kitchen is broken.

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#67]
<img width="1915" alt="screen shot 2016-10-10 at 12 23 16 pm" src="https://cloud.githubusercontent.com/assets/22300799/19243148/6148448e-8ee4-11e6-8eca-def6d60db98d.png">

**Comment by kalebheitzman** [comment]
This is back up. Looks like we'll eventually need to create a blank team-member template.
