### ISSUE TITLE
Cannot save page with "Planned giving" as parent

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#68]
When I save "Christ Church Permanent Funds" under "Give" it works fine. When I try to move it under "Planned Giving" I get this:

<img width="1616" alt="screen shot 2016-10-10 at 12 41 03 pm" src="https://cloud.githubusercontent.com/assets/22300799/19243733/d3190830-8ee6-11e6-85fc-cb294be547bc.png">

**Comment by kalebheitzman** [comment]
This was a permissions issue on the server. Now corrected.
