### ISSUE TITLE
Create Front Page Sermon/This Week Module

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#70]
Design:

![image](https://cloud.githubusercontent.com/assets/22300799/19246503/a7888fd4-8ef4-11e6-9a83-565fd6ef56a5.png)

Let's give it an alternate background color. Some light shade of blue or gray, maybe?

**Comment by kalebheitzman** [comment]
Use https://developers.soundcloud.com/docs/widget as a reference

**Comment by kalebheitzman** [comment]
This is up (need to figure out how we want to pull upcoming stuff but that's trivial).
