### ISSUE TITLE
Design tweaks for Cards

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#71]
- [x] Need to be able to use text formatting in the card "description" or body section. (See http://ccral.org/grow/acf for an example)
- [x] Would like cards to pop out a modal when clicked.

**Comment by kalebheitzman** [comment]
What content would be loading in the modal?

**Comment by kalebheitzman** [comment]
- summary/content
- video, audio, etc.
- add summary field

**Comment by kalebheitzman** [comment]
I've added a summary field that you can use markdown in for the card summary area. I

**Comment by kalebheitzman** [comment]
These now work (we can format them however next but I'd recommend something you can use site wide and not something specific for each page, i.e. make your content look good and reuse the same modal everywhere.
