### ISSUE TITLE
Is it possible to text-wrap around images?

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#72]
Specifically, I need to be able to do this within the expanders on the Parish History page (http://ccral.org/about/parish-history).

**Comment by kalebheitzman** [comment]
30% image width with css class.

**Comment by kalebheitzman** [comment]
You can now add a class to an image for this. The classes are .left and .right. You'll use this format for images:

```
![img](url){.right}
![img](url){.left}
```
