### ISSUE TITLE
Header / Footer Tweaks

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#74]
In Header:
- [x] Change "Link 3" to "Online Giving"
- [x] Set links for social buttons (on the header/footer) to open in new windows rather than navigating away from the site in the current window.
- [x] Change (Logo) Christ Church Raleigh to match this (as close as we can, might not be exact):

<img width="478" alt="screenshot 2016-10-08 12 03 55" src="https://cloud.githubusercontent.com/assets/22300799/19214362/56e098c0-8d4f-11e6-8cfe-1789227565d2.png">

In Footer:
- [x] Change "Birth" to "Birth + Adoption"
- [x] Under 5 p.m. on "Worship Times", add "Choral Evensong _(First Sunday each month)_" on the line after "Celtic Eucharist"

**Comment by kalebheitzman** [comment]
Can you create the logo as a graphic for Desktop/Tablet/Mobile? Trying to do this with CSS is getting really messy. Thanks!

**Comment by kalebheitzman** [comment]
I ended up fixing the graphic with css. We can tweak it for each device.
