### ISSUE TITLE
Ministry Themes for "Serve" search

### ISSUE THREAD

**Issue by jeremytackett** [HeitzmanCo/ChristChurchRaleigh-Theme#76]

**Comment by jeremytackett** [comment]
Disclaimer: this list may change, but this is a good start. Can we just have the ones with opportunities available show up in the dropdown? (Like, skip music if there are no music ones?)

- [ ] Children's Ministry
- [ ] Christian Formation
- [ ] Clerical / Admin. Asst.
- [ ] Communications
- [ ] Cooking / Hospitality
- [ ] Music
- [ ] Mentoring / Tutoring
- [ ] Outreach
- [ ] Parish Life
- [ ] Pastoral Care
- [ ] Serving in Worship
- [ ] Youth Ministry

**Comment by kalebheitzman** [comment]
This has been added and available.
