### ISSUE TITLE
Integrate Dropbox functionality into the site

### ISSUE THREAD

**Issue by kalebheitzman** [HeitzmanCo/ChristChurchRaleigh-Theme#8]
This is for pulling the latest PDF/DOC files into a downloadable area for front-end users.

**Comment by jeremytackett** [comment]
Login for CC Web Dropbox:

info@christchurchraleigh.org
Episcopal16

**Comment by kalebheitzman** [comment]
It looks like i have to make two http calls per file for this to work (and they're a bit slow). The best thing to do is just to copy the share link and paste it in a field for the sermon. We can also populate the "latest docs" section the same way. If latest docs is simple  the latest sermon docs than this is super easy. It's super easy either way. I'll go ahead and add a place to sermons to do this.

**Comment by kalebheitzman** [comment]
This is added now. I've also converted sermon type to audio type so it can be used generically across the site.
