### ISSUE TITLE
Final Website Tweaks

### ISSUE THREAD

**Issue by kalebheitzman** [HeitzmanCo/ChristChurchRaleigh-Theme#89]
- [ ] Serve dropdown to checkbox on backend
- [ ] Communications page under about jacked
- [ ] Connect page jacked up (grid problems)
- [ ] Kitchen page is blanking out
- [ ] Groups version of the serve page (Under extra ministry theme to group - type, don't need family friendly)
- [ ] Care dropdown doesn't work
- [ ] PDF Upload (Lay Volunteer schedules
- [ ] Parallax Headers
- [ ] Sermon Module on front page pull latest sermon (remove event calendar - data)
- [ ] Make times match 2:21 p.m.
- [ ] Grow/Youth header image/title look at confirmation page
- [ ] Confirmation page fix weird image duplication issue
- [ ] Image size for Header to Jeremy
- [ ] Round corners on sidebar images (rounding radius on staff page is - perfect, 4px)
- [ ] Change the way blockquotes look (confirmation page, see https://- incarnation.org/grow/baptisms/)
- [ ] Fix floating <p> on blockquotes
- [ ] Adjust h3 margins and h4 
- [ ] Remove bullet points from sidebar (confirmation milestones)
- [ ] Adjust H1's to be smaller (all headers)
- [ ] Change link colors to red/gold per branding (Gold is #F9C10C)
- [ ] Get rid of the loading bar
- [ ] Give Online / Change donation to contribution
- [ ] Give online change button color and text
- [ ] Convert online give to 1/3 and 2/3 and add Lorem
- [ ] Kill staff link in sidebars (see youth)
- [ ] Fix style on upcoming events (See youth sidebar)
- [ ] More subtle title boxes with parallax
- [ ] on youth page expanders (slide down instead of jump)
- [ ] planned giving page long list of names in columns /give/planned-giving/- mary-sumner-blunt rosters of giving
- [ ] Serve Volunteer ops create image spacer and fix learn more wrapping issue
- [ ] Serve Volunteer title make smaller on main index page
- [ ] Diaper Train When and Where text field not saving
- [ ] Grab give content from git update
- [ ] Header backgroud images super pixelated
- [ ] Page Header Module with parallax like confirmation
- [ ] Change yellow highlight to light blue for pastoral care cards
- [ ] Modal Close and round edges 
- [ ] Make Modal appear over chicken
- [ ] Diaper Train 2 signup buttons
- [ ] Address info on on serve stuff (make it readable)
- [ ] Email on serve page a live mailto
- [ ] Fix broken google image map (diaper train)
- [ ]

**Comment by jeremytackett** [comment]
- [ ] Add social media buttons to header
- [ ]

**Comment by kalebheitzman** [comment]
I'm tracking these in the shared Evernote Notebook. You should have them.
